source 'https://rubygems.org'

gem 'berkshelf', '~> 3.3.0'
gem 'thor-foodcritic'

group :integration do
  gem 'psych', '~> 2.0.5'
  gem 'test-kitchen', '~> 1.2.1'
  gem 'kitchen-vagrant'
  gem 'strainer', '~> 3.4.0'
  gem 'chefspec', '~> 3.4.0'
  gem 'travis-lint'
  gem 'rspec-expectations', '~> 2.14.0'
end
